package com.yalin.fidouaf.response;

public interface ErrorCode {
	int SUCCESS = 1200;
	int ACCEPT_NO_COMPLETE = 1202;
	int ERROR_BAD_REQUEST = 1400;
	int ERROR_UNAUTHORIZED = 1401;
	int ERROR_FORBIDDEN = 1403;
	int ERROR_NOT_FOUND = 1404;
	int ERROR_REQUEST_TIMEOUT = 1408;
	int ERROR_UNKNOWN_AAID = 1480;
	int ERROR_UNKNOWN_KEYID = 1481;
	int ERROR_CHANNEL_BINDING_REFUSED = 1490;
	int ERROR_REQUEST_INVALID = 1491;
	int ERROR_UNACCEPTABLE_AUTHENTICATOR = 1492;
	int ERROR_REVOKED_AUTHENTICATOR = 1493;
	int ERROR_UNACCEPTABLE_KEY = 1494;
	int ERROR_UNACCEPTABLE_ALGORITHM = 1495;
	int ERROR_UNACCEPTABLE_ATTESTATION = 1496;
	int ERROR_UNACCEPTABLE_CLIENT_CAPABLITIES = 1497;
	int ERROR_UNACCEPTABLE_CONTENT = 1498;
	int ERROR_INTERNAL_SERVER_ERROR = 1500;
}
